
CREATE TABLE users(
id SERIAL PRIMARY KEY,
nombre VARCHAR(100),
email VARCHAR(150),
password TEXT
);

CREATE TABLE clientes(
id SERIAL PRIMARY KEY,
nombre VARCHAR(120),
telefono VARCHAR(20),
activo BOOLEAN DEFAULT true
);

CREATE TABLE tours(
id SERIAL PRIMARY KEY,
nombre VARCHAR(120),
precio NUMERIC,
activo BOOLEAN DEFAULT true
);
